### ISSUE TITLE
broken link in the tarball hosted in pypi

### ISSUE THREAD

**Issue by pescobar** [sanger-pathogens/ariba#147]
When trying to build from sources using the tarball hosted in pypi I got this error:

`error: file ....../scripts/vcfcall_ariba.cpython-33m.so' does not exist`

I noticed that his issue was happening because the tarball in pypi has a broken link in `scripts/vcfcall_ariba.cpython-33m.so`

After downloading the tarball from github the installation worked fine.

**Comment by martinghunt** [comment]
Thanks for letting me know. I'll fix that in the next release when I upload to pypi.

**Comment by martinghunt** [comment]
The new version 2.4.0 has this fixed. Just uploaded to pypi.
