### ISSUE TITLE
compilation problem: ku128_v *r = &g->v.a[idd>>1].nei[idd&1];

### ISSUE THREAD

**Issue by rafalcode** [sanger-pathogens/ariba#159]
cc1 some warnings treated as erros
command gcc failed exit status 1

saying

third_party/fermi-lite-0.1/mag.c:246:2: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]

in relation to

ku128_v *r = &g->v.a[idd>>1].nei[idd&1];

So will try editing and:
ku128_v *r;
r = &g->v.a[idd>>1].nei[idd&1];

Appears C90 std is fussy with this . Is C90 stipulation  necessary?

**Comment by martinghunt** [comment]
What OS and what version of gcc are you using?
