### ISSUE TITLE
problems with fermilite

### ISSUE THREAD

**Issue by karinlag** [sanger-pathogens/ariba#169]
Hi!

I am able to install ariba without any issues, but, I do get the following error when I try to run it:

```
(ariba)[karinlag@abel ariba]$ ariba --help
Traceback (most recent call last):
  File "/work/projects/nn9305k/bin/virtenv/ariba/bin/ariba", line 3, in <module>
    import ariba
  File "/work/projects/nn9305k/bin/virtenv/ariba/lib/python3.5/site-packages/ariba/__init__.py", line 55, in <module>
    from ariba import *
  File "/work/projects/nn9305k/bin/virtenv/ariba/lib/python3.5/site-packages/ariba/assembly.py", line 6, in <module>
    import fermilite_ariba
ImportError: /cluster/software/VERSIONS/intel-2017.1/advisor_2017.1.1.486553/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /work/projects/nn9305k/bin/virtenv/ariba/lib/python3.5/site-packages/fermilite_ariba.cpython-35m-x86_64-linux-gnu.so)
(ariba)[karinlag@abel ariba]$
```

I believe this is Heng Li's fermi-lite, is it not? If so, I will take the issue there. I have a sneaking suspicion this is down to which intel something-or-other that I have loaded, but no clue of how to figure out what I need...

**Comment by martinghunt** [comment]
This is an issue with compiling the C++ ariba code, not fermilite itself, so don't take the issue to fermi-lite. Can you try downloading the release tarball and running "python3 setup.py test". That compiles all the C/C++ code and runs the tests. I think the output will be more verbose than using pip, and also pip doesn't run the tests.

**Comment by karinlag** [comment]
Ahhhh! (definite lightbulb moment!). Now I understand a lot more! I will do that presently. Any specifics on compiler versions etc? I have around 11 available.

**Comment by martinghunt** [comment]
I deliberately didn't use any c++11, so old compilers should be ok. I'm using gcc 4.6.3, which is 5 years old. It's the oldest compiler I've tested ariba on.

First I would try whatever the default is on your system, by not changing anything and running `python3 setup.py test`. That will compile the code. If you try to change your compiler, then compile, you'll like run into errors like the one above when you run ariba.

**Comment by karinlag** [comment]
I forgot to say that I figured out what the problem is. The python3 that was on the cluster was compiled with icc, and that seemed to be incompatible with the things in ariba. But, I installed anaconda, and I managed to get it to work then.
