### ISSUE TITLE
How to input several fastq files for pooled assembly?

### ISSUE THREAD

**Issue by VadimDu** [sanger-pathogens/ariba#171]
Dear developers,

I am excited to use ARIBA program, I have a question though about how exactly input files. 
In the manual it says "ariba run prepareref_dir, reads_1, reads_2, outdir"
Suppose I have f1-for, f2-for, f3-for and f1-rev, f2-rev, f3-rev; How can I specify ariba to assemble them together (pooled)?

Many thanks
Vadim D

**Comment by martinghunt** [comment]
Sorry but there is no option to take multiple reads files in that way.
You'll need to cat the forward reads into one file and the reverse reads into another file, then use those two files as input.

**Comment by VadimDu** [comment]
Thank you for the replay, that is exactly what I did, worked just fine.

I have another small question if you do not mind, where can I find/can you provide information about interpreting all the different columns in 'report.tsv' file? I will be happy to understand better what each one means.

Best regrads
Vadim D

**Comment by martinghunt** [comment]
There is a description here:
https://github.com/sanger-pathogens/ariba/wiki/Task:-run

Hope that helps,
Martin
