### ISSUE TITLE
Curious output

### ISSUE THREAD

**Issue by karinlag** [sanger-pathogens/ariba#172]
Hi! Running 2.9 here. Whenever I run something, I get this out:

self.mlst_profile_file /home/karinlag/PycharmProjects/testdata/fastq_files/mlst_db/ref_db/pubmlst.profile.txt
self.report_file_filtered /home/karinlag/PycharmProjects/testdata/fastq_files/Angen-bacDNA2-78-2013-01-4718_S29_L001/report.tsv

(of course changing with the input)

Is this supposed to happen....?

**Comment by martinghunt** [comment]
Oops! Thanks for letting me know. That's some deubgging output that needs removing. You can ignore it.

I guess you have it installed successfully? Would be handy if you could comment on issue #169 if it might be of help to others.

**Comment by karinlag** [comment]
Thanks for letting me know, got a bit confusing there...

Not managed to finish the install on the cluster yet, working on a pipeline on my local machine for now while waiting for support from IT.

**Comment by martinghunt** [comment]
OK, good luck! I've removed those print statements and there is a new release 2.9.1.
