### ISSUE TITLE
micplot requires X window

### ISSUE THREAD

**Issue by simonrharris** [sanger-pathogens/ariba#176]
By default matplotlib uses an X window backend. micplot will therefore die if one isn't available. Can be fixed by adding this before any pyplot import

import matplotlib
matplotlib.use('Agg')

**Comment by martinghunt** [comment]
I'll get round to doing this soon (unless you want to send a PR ;) ) but I think for now this will fix it:
`export MPLBACKEND="agg"`.

**Comment by andrewjpage** [comment]
Fixed in v2.10.4
