### ISSUE TITLE
pubmlstget does not work with docker

### ISSUE THREAD

**Issue by thanhleviet** [sanger-pathogens/ariba#180]
When I run this command `docker run --rm -it -v $(pwd):/data/ sangerpathogens/ariba ariba pubmlstget "Staphylococcus aureus" get_mlst` 
The get_mlst was expected to be in the current directory I run the command but it was not, event when I replaced `$(pwd)` with an absolute path, i.e. `/home/ubuntu/mlst:/data` but It did not work either.

BUT....
If I logged in docker container with `docker run --rm -it -v $(pwd):/data/ sangerpathogens/ariba` and run` ariba pubmlstget "Staphylococcus aureus" get_mlst` , it worked, and get_mlst appeared on the host

**Comment by martinghunt** [comment]
You need to do `/data/get_mlst` at the end, ie:

    docker run --rm -it -v $(pwd):/data/ sangerpathogens/ariba ariba pubmlstget "Staphylococcus aureus" /data/get_mlst

**Comment by thanhleviet** [comment]
Thank @martinghunt. It works now. 
Did I ignore this instruction written somewhere in the wiki?

**Comment by martinghunt** [comment]
No you didn't, I should probably add example calls when using docker to the wiki...

**Comment by thanhleviet** [comment]
@martinghunt Though your explanation made it worked but when I executed `ariba run get_mlst/ref_db reads_1.fq reads_2.fq ariba_out` with the fastq files correctly put in the $(pwd). I have found out that the docker image was not built in a proper way (my sense :)), and it's not quite safe to have root account owning the result folders. So I come up with my Dockerfile which I copied some code from biocontainers

`FROM sangerpathogens/ariba

RUN mkdir /data

#Code copied from biocontainers 
RUN groupadd fuse && \
    useradd --create-home --shell /bin/bash --user-group --uid 1000 --groups sudo,fuse biodocker && \
    echo `echo "biodocker\nbiodocker\n" | passwd biodocker` && \
    chown biodocker:biodocker /data

USER biodocker

VOLUME /data

CMD ["/bin/bash"]

WORKDIR /data`


With this docker image, I can run smoothly the commands written on the wiki, such as:
`docker run --rm -it -v $(pwd):/data/ thanhleviet/ariba ariba pubmlstget "Staphylococcus aureus" get_mlst` 

I will have a get_mlst folder inside the `$(pwd)`

`docker run --rm -it -v $(pwd):/data/ thanhleviet/ariba ariba run get_mlst/ref_db reads_1.fq reads_2.fq ariba_out`

And result folders have non-root permission.

**Comment by martinghunt** [comment]
You could run this on the existing docker container:

    docker run --rm -it -v $PWD:/data sangerpathogens/ariba ariba run /data/get_mlst/ref_db /data/reads_1.fq /data/reads_2.fq /data/ariba_out

ie /data is needed in front of the paths. The resulting ariba_out directory is not owned by root.

**Comment by thanhleviet** [comment]
Understood! Thank you. 
I ran the command:
`docker run --rm -it -v $(pwd):/data sangerpathogens/ariba ariba run /data/mlst_get/ref_db /data/data/50_S14_L001_1P.fastq /data/data/50_S14_L001_2P.fastq /data/test1`

It works but ....the folder is owned by root 
`drwxr-xr-x  2 root   root   4.0K May 30 13:43 test1`

**Comment by martinghunt** [comment]
That's interesting. When I run it (using a mac) I get this:
`drwxr-xr-x   9 mhunt  EBI\Domain Users   306B 30 May 13:55 ariba_out`
Sorry, but I've no idea why the difference.

**Comment by thanhleviet** [comment]
Those commands I ran on Ubuntu.
I have just replicated on my mac and the folders are not owned by root. 
`0 drwxr-xr-x  5 thanhlv  staff   170B May 30 14:58 get_mlst/`

I guess probably due to Mac uses virtual machine to run docker while Ubuntu uses docker directly. :)
Interesting! Anw, thanks for your help.

**Comment by martinghunt** [comment]
Thanks. I'll look into changing the docker so it works more easily on ubuntu as well. Thanks for the dockerfile fix!
