### ISSUE TITLE
python3.4 pip upgrade C90 mixed declar and code error

### ISSUE THREAD

**Issue by rafalcode** [sanger-pathogens/ariba#183]
Hi,
Couldn't upgrade on python3.4 due to infamous C90 no mixed declaration and code error coming out of mag.c line 246 (mag_eh_markdel func). My default gcc is 4.4.7 ... I'm fairly sure it's not hardwired for "-std=C90" though.
Cheers.

**Comment by andrewjpage** [comment]
gcc 4.4.7 was released more than 5 years ago & python 3.4 was released 3 years ago. I'm afraid we dont have the resources to test on older platforms. I would recommend updating to more recent versions and trying again.
