### ISSUE TITLE
How to detect presence or absence of a sequence carrying a deletion

### ISSUE THREAD

**Issue by bioprojects** [sanger-pathogens/ariba#184]
Dear Martin,

Thank you so much again for explaining ARIBA 
during the conference ABPHM2017 in Sanger in May.

I do think ARIBA is a really nice, well-designed, 
generally useful tool.

I'm trying to detect presence or absence of a promoter
sequence carrying a deletion associated with AMR.

When I used the sequence carrying the deletion as a reference,
a report of ARIBA run for a sample without carrying the deletion is
http://yahara.hustle.ne.jp/projects/ariba/report.tsv
in which column T (ref_ctg_effect) is correctly indicated as "INS".

However, ARIBA summary for the report 
http://yahara.hustle.ne.jp/projects/ariba/out.summary.csv
says "mtrR_Adel_promoter.match" is yes.

But this sample does not have the deletion, so I would like to 
have a summary in which "mtrR_Adel_promoter.match" is no.

Of course I read definition of "match" judged by the summary command
https://github.com/sanger-pathogens/ariba/wiki/Task:-summary

Is ARIBA not designed to detect this kind of deletion?
I appreciate your comment.
Thanks a lot in advance.

Best wishes,

Koji

***
Koji Yahara
Senior Research Fellow
Antimicrobial Resistance Research Center
National Institute of Infectious Diseases
4-2-1 Aobacho, Higashimurayama, Tokyo
189-0002 Japan
Tel: +81-42-561-0771 (Ex. 3539)

**Comment by martinghunt** [comment]
Ariba does detect it, in the sense that it is reported in `report.tsv` - this is where you will need to look to be sure exactly what happened. The summary can't catch every case and while developing ariba different users wanted different incompatible behaviours for what summary counts as a "match". This is the reason for the extra columns. You could use the pct_id or novel_var columns from summary to identify samples that do not match perfectly. Ultimately, every use case is different and sorry but it's impossible to get ariba summary to behave in a way that works for everyone.

**Comment by bioprojects** [comment]
Thank you very much for your answer.  OK, I've understood it!
