### ISSUE TITLE
Creation of custom variant database containing indels, both in-frame or frameshifts 

### ISSUE THREAD

**Issue by dsarov** [sanger-pathogens/ariba#189]
Hello Ariba creators,

Thanks very much for writing this software.

I'm wondering if there is a way to create a custom database that includes different types of mutations rather than just SNPs? When I try to create a custom DB with indels the sanity checks in the aln2meta script don't like the formatting of the variant column of the tsv file. The SNP variants are okay but I can't figure out what format things like frameshifts (e.g. L295fs) or in-frame deletions (L294-D295del) should be? 

Is Ariba capable of looking at these type of variants and I'm just missing something obvious?

Thanks for your time.

Regards,

Derek

**Comment by martinghunt** [comment]
You can only put SNPs in (not indels) for "known variants" for aln2meta and prepareref. But ARIBA reports all the indels and frameshifts that it finds in the report TSV file, which means you can still get all the info on those variants.

**Comment by dsarov** [comment]
No worries. Thanks for the info!

Cheers,

Derek
