### ISSUE TITLE
How ariba deal with reads mapped to multiple clusters

### ISSUE THREAD

**Issue by IEkAdN** [sanger-pathogens/ariba#198]
Hello,

I would like to use ariba without cd-hit clustering. When two similar reference sequences exist, I guess some sequence reads will be mapped to both of them (in other words, some reads will be mapped to two clusters). In such a case, how does ariba deal with these reads? Does ariba use these reads for local assemblies in both of these two clusters?

**Comment by martinghunt** [comment]
Yes, reads can be put into more than one cluster. Reads are allocated to every cluster where either read of the pair matches any sequence in that cluster.

**Comment by IEkAdN** [comment]
Thank you for your quick response. Then I will try ariba without cd-hit clustering.
