### ISSUE TITLE
Ariba fails when using NFS directories for output

### ISSUE THREAD

**Issue by thomcuddihy** [sanger-pathogens/ariba#203]
`shutil.rmtree` calls fail when the root_dir is an NFS volume. This due to how NFS handles files that are opened and then deleted while still open by silly renaming them.

Use `ariba run --noclean ...` or output to a non-NFS directory (and then move if needed) to circumvent issue.

Fix issue by explicitly closing files. I'll send through a pull request if I have time.

**Comment by thomcuddihy** [comment]
Or, of course, set `--tmp_dir` to a non-NFS location too :)

**Comment by martinghunt** [comment]
What errors do you get? Which files are left open? I just ran `ariba test` on an NFS file system, with `ARIBA_TMPDIR=$PWD` and it worked ok.
