### ISSUE TITLE
Problems Task getref  xxxxFinder and CARD

### ISSUE THREAD

**Issue by Coldheart79** [sanger-pathogens/ariba#211]
We are having problems download the data from CGE (-finder databases) 

ariba getref resfinder out.resfinder
Downloading data with:
curl -X POST --data "folder=resfinder&filename=resfinder.zip" -o resfinder.zip https://cge.cbs.dtu.dk/cge/download_data.php
The following command failed with exit code 127
curl -X POST --data "folder=resfinder&filename=resfinder.zip" -o resfinder.zip https://cge.cbs.dtu.dk/cge/download_data.php

The output was:

/bin/sh: 1: curl: not found

**Comment by Coldheart79** [comment]
I also started experience problems with CARD after their maintenance shut-down last week.

**Comment by Coldheart79** [comment]
Should mention no problems with the other databases, but unable to download any of the ones are CGE and CARS.

**Comment by ssjunnebo** [comment]
The CARD issue was fixed in the latest version (2.11.1). 

For resfinder, you need to install curl.
