### ISSUE TITLE
Necessity of spades executable?

### ISSUE THREAD

**Issue by karinlag** [sanger-pathogens/ariba#214]
Hi!

I'm using ariba on a cluster, where I have to activate various software explicitly.

I just installed the current version, and ran ariba test out to make sure everything is fine. However, I get plenty of warnings re spades missing. However, it doesn't say anywhere that it needs spades, and also it seems to say that things are fine anyhow. So, thus: does it actually want spades available on the command line?

**Comment by martinghunt** [comment]
Spades was recently added as an alternative assembler to fermilite. ARIBA defaults to use fermilite, not spades. So, no it doesn't want spades and won't be using it unless you said `--assembler spades`. Just ignore the warnings.

I'll leave this open, as ARIBA shouldn't be warning about spades unless you choose to use it.

**Comment by karinlag** [comment]
Thanks for letting me know, I was starting to wonder if there was something big that I had missed.

**Comment by martinghunt** [comment]
Fixed in release 2.12.0
