### ISSUE TITLE
PlasmidFinder databases have moved

### ISSUE THREAD

**Issue by andrewjpage** [sanger-pathogens/ariba#218]
ARIBA is pointing to an archived copy of the PlasmidFinder databases. The current ones are at:

https://bitbucket.org/genomicepidemiology/plasmidfinder_db/raw/master/enterobacteriaceae.fsa
https://bitbucket.org/genomicepidemiology/plasmidfinder_db/raw/master/gram_positive.fsa

**Comment by martinghunt** [comment]
@snogu Sorry but at the moment you'll have to use the old ones that getref gets, or use the hack below...

The downloading code in ariba will need a rewrite to get all the data from the bitbucket links that @andrewjpage put above. This looks to be true for all the *finder datasets. I'll get round to it sometime (I'm maintaining ariba in my spare time).

Here's a hack that at least gets prepareref to run for me with no errors:

    wget https://bitbucket.org/genomicepidemiology/plasmidfinder_db/raw/master/gram_positive.fsa
    wget https://bitbucket.org/genomicepidemiology/plasmidfinder_db/raw/master/enterobacteriaceae.fsa
    cat enterobacteriaceae.fsa  gram_positive.fsa  | sed 's/\s*$//'  | sed 's/_/./' > seqs.fa
    awk '$1~/^>/ {OFS="\t"; print substr($1,2),0,0,".",".","."}' seqs.fa > seqs.tsv
    ariba prepareref -f seqs.fa -m seqs.tsv OUT

Note: this hack loses the information about the original sequence names.

**Comment by snogu** [comment]
Thanks for the quick answer @martinghunt , seems to work nicely :)

**Comment by martinghunt** [comment]
Fixed in release 2.12.0
