### ISSUE TITLE
segmentation fault when I import ariba

### ISSUE THREAD

**Issue by benjaminfang** [sanger-pathogens/ariba#230]

**Comment by benjaminfang** [comment]
I tested this and  think this error caused by  matplotlib module.

/Python/python_v3.6.5/lib/python3.6/site-packages/ariba/mic_plotter.py
(line 9-12)

**Comment by kpepper** [comment]
Hi **@benjaminfang**, can you please provide more detalls, e.g. stack trace etc. Try the new release in Pypi to see if that fixes it.

**Comment by kpepper** [comment]
Closing this issue due to lack of details.
