### ISSUE TITLE
Antibiotic resistance/susceptibility panel?

### ISSUE THREAD

**Issue by ssjunnebo** [sanger-pathogens/ariba#232]
From a recent path-help ticket:

Is there any function that allows to get a plain antibiotic resistance/susceptibility panel such as the one from Mykrobe predictor?
If not, do you plan to implement something similar?

**Comment by martinghunt** [comment]
I can only make time for bug fixes, not feature development. Pull requests are welcome :)

**Comment by ssjunnebo** [comment]
Of course! Thanks :)
