### ISSUE TITLE
resfinder line breaks problem

### ISSUE THREAD

**Issue by schultzm** [sanger-pathogens/ariba#236]
Thanks for writing `ariba`.  I was just looking through your code in https://github.com/sanger-pathogens/ariba/blob/master/ariba/ref_genes_getter.py . At line 460  I see you have a method to fix line breaks in virulence_finder_db.  @tseemann has shown me that the resfinder db, also from the CGE, has the same problem with line breaks.  @tseemann has emailed the CGE to fix it, but it seems to be a recurring issue with updates to that database.  Could you please patch ref_genes_getter.py to deal with this problem?

Regards,

**Comment by martinghunt** [comment]
Thanks for letting me know. I'll apply that same function to the resfinder fasta ...

**Comment by martinghunt** [comment]
Apologies for only just getting round to this! I have very little time to work on ariba. It's fixed in new release 2.13.0
