### ISSUE TITLE
Stopping! Signal received: 13

### ISSUE THREAD

**Issue by schultzm** [sanger-pathogens/ariba#238]
Hi, 

Thanks for writing the very useful `Ariba`.   

During my recent use of version `2.12.1`, `Ariba` finished successfully; however, if I don't use the `--verbose` option, the last message I see (printed to `stdout`, line [196](https://github.com/sanger-pathogens/ariba/blob/master/ariba/clusters.py)) is `Stopping! Signal received: 13`.  From what I can tell, this means:
```
      SIGPIPE      13       Term    Broken pipe: write to pipe with no
                                     readers; see pipe(7)
```

Are you able to confirm that this is the correct behaviour?  If it is, can you please hide this message?  Else, can you tell me what is going wrong?

Thanks,

**Comment by martinghunt** [comment]
Ignore it. I think it started happening after multithreading for bowtie2 and spades was added back in as an option (#210). Sorry, I don't what's causing that to be output.

**Comment by JFsanchezherrero** [comment]
Hi there, 
Should I worry about receiving this signal in my data? Has ariba finished succesfully or should I tried again?
Thanks

**Comment by kpepper** [comment]
Where abouts in the log does it appear?

**Comment by JFsanchezherrero** [comment]
Hi there, 
As it makes ariba to stop so appears at the end of the log. But I don't know if it finished properly. Basically, no other messages are provided.

The command I sent was:

`ariba run --threads 8 VFDB_data sample_R1.fastq sample_R2.fastq output_example`

**Head of the log file:**
> adsA detected 1 threads available to it
> cap8B detected 1 threads available to it
> cap8E detected 1 threads available to it
>....

**Tail of the log file:**
>....
> sdrC reported completion
> sdrE reported completion
> sea detected 8 threads available to it
> sea reported completion
> Stopping! Signal received: 13

No further details were provided and no any other messages were prompt.
Jose

**Comment by kpepper** [comment]
Hi **@JFsanchezherrero**, if you get all the report tsv files it should be okay. However, if you're concerned then you could always try the latest version - v2.13.5 from PyPI or Bioconda, or use the Docker image which has all the dependencies bundled in:

docker pull sangerpathogens/ariba

Instructions for this are on there Github pages/Wiki.

**Comment by JFsanchezherrero** [comment]
Thanks.
I will take a look.

**Comment by kpepper** [comment]
FYI, release v2.14.1 includes a fix for this "Stopping" issue.

**Comment by JFsanchezherrero** [comment]
Dear developers,

I successfully update ariba within my environment using 

> pip install --upgrade ariba

```
(my_env) jsanchez@cacau:/my_folder/test$ pip install --upgrade ariba
Collecting ariba
  Downloading https://files.pythonhosted.org/packages/fd/ff/be0df07ed469cb55e951fda3cf81102f54729a253f2dacdb719831abb8a2/ariba-2.14.1.tar.gz (2.7MB)
    100% |████████████████████████████████| 2.7MB 749kB/s 
Requirement already satisfied, skipping upgrade: BeautifulSoup4>=4.1.0 in /my_env/lib/python3.5/site-packages (from ariba) (4.7.1)
Requirement already satisfied, skipping upgrade: biopython in /my_env/lib/python3.5/site-packages (from ariba) (1.73)
Requirement already satisfied, skipping upgrade: dendropy>=4.2.0 in /my_env/lib/python3.5/site-packages (from ariba) (4.4.0)
Requirement already satisfied, skipping upgrade: matplotlib in /my_env/lib/python3.5/site-packages (from ariba) (2.2.4)
Requirement already satisfied, skipping upgrade: pyfastaq>=3.12.0 in /my_env/lib/python3.5/site-packages (from ariba) (3.17.0)
Requirement already satisfied, skipping upgrade: pysam>=0.9.1 in /my_env/lib/python3.5/site-packages (from ariba) (0.15.2)
Requirement already satisfied, skipping upgrade: pymummer<=0.10.3 in /my_env/lib/python3.5/site-packages (from ariba) (0.10.3)
Requirement already satisfied, skipping upgrade: soupsieve>=1.2 in /my_env/lib/python3.5/site-packages (from BeautifulSoup4>=4.1.0->ariba) (1.9)
Requirement already satisfied, skipping upgrade: numpy in /my_env/lib/python3.5/site-packages (from biopython->ariba) (1.16.4)
Requirement already satisfied, skipping upgrade: setuptools in /my_env/lib/python3.5/site-packages (from dendropy>=4.2.0->ariba) (41.0.0)
Requirement already satisfied, skipping upgrade: cycler>=0.10 in /my_env/lib/python3.5/site-packages (from matplotlib->ariba) (0.10.0)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.1 in /my_env/lib/python3.5/site-packages (from matplotlib->ariba) (2.8.0)
Requirement already satisfied, skipping upgrade: pytz in /my_env/lib/python3.5/site-packages (from matplotlib->ariba) (2018.9)
Requirement already satisfied, skipping upgrade: six>=1.10 in /my_env/lib/python3.5/site-packages (from matplotlib->ariba) (1.12.0)
Requirement already satisfied, skipping upgrade: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /my_env/lib/python3.5/site-packages (from matplotlib->ariba) (2.4.0)
Requirement already satisfied, skipping upgrade: kiwisolver>=1.0.1 in /my_env/lib/python3.5/site-packages (from matplotlib->ariba) (1.0.1)
ariba 2.14.1 has requirement matplotlib>=3.1.0, but you'll have matplotlib 2.2.4 which is incompatible.
Installing collected packages: ariba
  Found existing installation: ariba 2.13.5
    Uninstalling ariba-2.13.5:
      Successfully uninstalled ariba-2.13.5
  Running setup.py install for ariba ... done
Successfully installed ariba-2.14.1
```
But the thing is if I try to use ariba it keeps on complaining.

```
(my_env) jsanchez@cacau:/my_folder/test$ ariba -h
Traceback (most recent call last):
  File "/my_env/bin/ariba", line 3, in <module>
    import ariba
  File "/my_env/lib/python3.5/site-packages/ariba/__init__.py", line 57, in <module>
    from ariba import *
  File "/my_env/lib/python3.5/site-packages/ariba/ref_genes_getter.py", line 614
    print(f"E-fetching {len(acc_list)} genbank records from BioProject {BIOPROJECT} and writing to.  This may take a while.", file=sys.stderr)
                                                                                                                           ^
SyntaxError: invalid syntax
```

Is it because there is the dependency on matplolib that is not fulfilled? Or is it related to the new content you added it?

Thanks.

**Comment by kpepper** [comment]
It needs Python 3.6 now - try upgrading Python version to 3.6 and see if that helps.

**Comment by JFsanchezherrero** [comment]
Thank you very much for that quick response.
I will let you know when I could have Python 3.6 in the system, depends on IT dept.

**Comment by kpepper** [comment]
As stated previously, release v2.14.1+ includes a fix for this issue.
