### ISSUE TITLE
NCBI database.

### ISSUE THREAD

**Issue by KatherineJ-H** [sanger-pathogens/ariba#241]
Is there any way to add the NCBI database to the list of getrefs?
It states in the wiki that you can add your own database but I can't seem to find accurate instructions to do so, is there any way you could add NCBI to the list?
https://www.ncbi.nlm.nih.gov/bioproject/PRJNA313047

**Comment by martinghunt** [comment]
There are instructions here for how to use a custom database with ariba:
https://github.com/sanger-pathogens/ariba/wiki/Task:-prepareref
If those sequences are all genes, and you only need to identify them as present or absent in samples (a quick look at the description suggests that this is the case), then you'd need to make a fasta file of the nucleotide sequences and run this:

    ariba prepareref --all_coding yes -f in.fasta out_dir

Sorry, but it's unlikely that it will get added to the getref list. Pull requests are welcome, however!

**Comment by KatherineJ-H** [comment]
Hello Martin, thank you for getting back to me so quickly.

I have tried what you suggested but it keeps returning a file not found error for my fasta file. Is there a certain location I should place it to be found in the path?

Many Thanks

Kate

________________________________

**Comment by martinghunt** [comment]
What is the command you're running at what's the output? Could you copy and paste your terminal here please?

**Comment by KatherineJ-H** [comment]
Hello Martin, I meant to email you this morning about this.

I actually worked it out, it was one of those just needed someone to point out an obvious error situations.

Sorry to have bothered you!

Thank you again for all of your help.

Best Wishes

Kate

________________________________

**Comment by martinghunt** [comment]
That's ok! It would be useful to know if you do get it working with ARIBA, and how you did it.
