### ISSUE TITLE
Also getting Stopping! Signal received: 13

### ISSUE THREAD

**Issue by Siacm** [sanger-pathogens/ariba#249]
Hi, I'm using version 2.13.1, and I'm getting the same "Stopping! Signal received: 13 message" after  each input. There seems to be nothing wrong with the output file log, but it is printing that message out to the screen.

**Comment by martinghunt** [comment]
Ignore it. I think it started happening after multithreading for bowtie2 and spades was added back in as an option (#210). Sorry, I don't what's causing that to be output.

**Comment by kpepper** [comment]
Fixed in release v2.14.1.
