### ISSUE TITLE
Allow increasing cd-hit-est memory allocation

### ISSUE THREAD

**Issue by simonrharris** [sanger-pathogens/ariba#255]
When running prepareref on a large input fasta file I get the following error from cd-hit-est

Fatal Error:
not enough memory, please set -M option greater than 1212

Program halted !!

Currently it appears it is not possible to increase this cd-hit-est option via the prepareref options. Could an option be added to allow this to be increased when necessary?

**Comment by kpepper** [comment]
This option has now been added in release v2.13.4 of Ariba. Use the --cdhit_max_memory command line argument to specify the cdhit memory in MB.

**Comment by kpepper** [comment]
Now available in pypi.
