### ISSUE TITLE
Several "At least one cluster failed!Stopping..." errors

### ISSUE THREAD

**Issue by BaMagalhaes** [sanger-pathogens/ariba#261]
I tried to use ariba with the command:

`$ ariba run out.card.prepareref 25164_R1.fastq.gz 25164_R2.fastq.gz out.run
`
However I got the following errors

```
Stopping! Signal received: 13
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ariba/clusters.py", line 602, in run
    self._run()
  File "/usr/lib/python3/dist-packages/ariba/clusters.py", line 636, in _run
    raise Error('At least one cluster failed! Stopping...')
ariba.clusters.Error: At least one cluster failed! Stopping...

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/ariba", line 298, in <module>
    args.func(args)
  File "/usr/lib/python3/dist-packages/ariba/tasks/run.py", line 65, in run
    c.run()
  File "/usr/lib/python3/dist-packages/ariba/clusters.py", line 605, in run
    raise Error('Something went wrong during ariba run. Cannot continue. Error was:\n' + str(err))
ariba.clusters.Error: Something went wrong during ariba run. Cannot continue. Error was:
At least one cluster failed! Stopping...
```
None of the solutions suggested in previous closed issues helped to solve these errors. I have tried it using the option `--threads 1` , didn't help. 

Is it a bug? Do you have any other suggestions?

**Comment by kpepper** [comment]
Do you get a log.clusters file in the output folder? If so, what's been logged in it?
Also, do you get any extra information using the --verbose flag?
What version shows when you execute 'ariba version'
Are you able to provide access to the fastq files?

**Comment by BaMagalhaes** [comment]
I send attached all the files I get as output on the out.run folder, as
well as the original fastq.gz files.
When I use the --verbose flag I get the same error message, without any
additional information.
I'm using the ariba v. 2.11.1, which I installed using "sudo apt-get
install ariba" in Ubuntu 18.04.

 25164_R1.fastq.gz
<https://drive.google.com/file/d/1uu-zgd2UhRNoUAQUeEBDTpx1KNm4LG95/view?usp=drive_web>
 25164_R2.fastq.gz
<https://drive.google.com/file/d/1BFinhuu6iZC2-6T_NmAVwDYt3K1nLkCu/view?usp=drive_web>
Thank you for your help!

**Comment by kpepper** [comment]
Hi **@BaMagalhaes**, 
So, I ran your files on a Mac Ariba install and it produced a report.tsv with no errors. 
I ran an older Ariba release on Ubuntu 12 and got a Signal message but still ran to completion and produced a report.tsv. It didn't abort.
I then ran your files through the latest Ariba release on Ubuntu 17 via the docker image - again ran to completion with no errors.

The version of Ariba available in Debian is now rather out of date (the latest Ariba release is v2.13.15). I would suggest using the latest Ariba release via pip3 install or using the Docker hub image, which worked for me - see the Github page for instructions.

**Comment by BaMagalhaes** [comment]
I had indeed an older version of Ariba. Thus, I removed the package,
installed it again with pip3, ran it the same command but the same errors
occurred:

'$ariba run --verbose out.card.prepareref' 25164_R1.fastq.gz
25164_R2.fastq.gz out.run
Found reads file: 25164_R1.fastq.gz
Found reads file: 25164_R2.fastq.gz
ARIBA version: 2.13.5

External dependencies:
bowtie2 2.3.4.1 /usr/bin/bowtie2
cdhit 4.7 /usr/bin/cd-hit-est
nucmer 3.1 /usr/bin/nucmer

External dependencies OK: True

Python version:
3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0]

Python packages:
ariba 2.13.5
/home/localadmin/.local/lib/python3.6/site-packages/ariba/__init__.py
bs4 4.6.0 /usr/lib/python3/dist-packages/bs4/__init__.py
dendropy 4.3.0 /usr/lib/python3/dist-packages/dendropy/__init__.py
pyfastaq 3.17.0 /usr/lib/python3/dist-packages/pyfastaq/__init__.py
pymummer 0.10.3 /usr/lib/python3/dist-packages/pymummer/__init__.py
pysam 0.14 /usr/lib/python3/dist-packages/pysam/__init__.py

Python packages OK: True

Everything looks OK: True'

(...)

Error:
'Final value of remaining_clusters counter: Value('l', 81)
Stopping! Signal received: 13
Finished assembling clusters

Traceback (most recent call last):
  File
"/home/localadmin/.local/lib/python3.6/site-packages/ariba/clusters.py",
line 612, in run
    self._run()
  File
"/home/localadmin/.local/lib/python3.6/site-packages/ariba/clusters.py",
line 646, in _run
    raise Error('At least one cluster failed! Stopping...')
ariba.clusters.Error: At least one cluster failed! Stopping...

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/localadmin/.local/bin/ariba", line 310, in <module>
    args.func(args)
  File
"/home/localadmin/.local/lib/python3.6/site-packages/ariba/tasks/run.py",
line 65, in run
    c.run()
  File
"/home/localadmin/.local/lib/python3.6/site-packages/ariba/clusters.py",
line 615, in run
    raise Error('Something went wrong during ariba run. Cannot continue.
Error was:\n' + str(err))
ariba.clusters.Error: Something went wrong during ariba run. Cannot
continue. Error was:
At least one cluster failed! Stopping...'

After this I removed the package again and tried to installed it with
docker but instead got another error (I believe not related to this
subject):
'$ docker pull sangerpathogens/ariba
Command 'docker' is available in '/snap/bin/docker'
The command could not be located because '/snap/bin' is not included in the
PATH environment variable.
docker: command not found'

I'm a bit stuck at the moment with this docker problem, but I'll try to
solve it and see if this installation is the solution for these errors.

**Comment by kpepper** [comment]
Does it exit immediately, or do you get some output such as:

AAC_3__Ib detected 1 threads available to it
AAC_3__Ib reported completion
APH_3___IIb detected 1 threads available to it
APH_3___IIb reported completion
etc.

Is there anything at all in the out.run folder?

To access Docker you could do the following:
export PATH=/snap/bin/:$PATH
to add docker to your path before running the command. Do you have a sysadmin who can check that it's installed properly?

**Comment by BaMagalhaes** [comment]
I did get something like that as output but there was nothing else, apart
from what I showed you previously, in the out.run folder.

Thank you for your help with docker. I manage to install Ariba after
exporting  /snap/bin to PATH and adding my user to my docker group, since
I'm running the program as a non-root user.
I used the command :
$ docker run --rm -it -v home/ubuntu/data:/data sangerpathogens/ariba ariba
run --verbose out.card.prepareref 25164_R1.fastq.gz 25164_R2.fastq.gz
out.run

but I get the error:
docker: Error response from daemon: create home/ubuntu/data:
"home/ubuntu/data" includes invalid characters for a local volume name,
only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a
host directory, use absolute path.
See 'docker run --help'.

I just simply copied my files (25164_R1.fastq.gz,  25164_R2.fastq.gz,
out.card.prepareref) to home/ubuntu/data with sudo mv.

I'm sorry for the spamming with simple/obvious questions, but it's the
first time I run a program with docker.

**Comment by kpepper** [comment]
Are you missing a / in front of home/ubuntu... i.e. /home/ubuntu ?

**Comment by BaMagalhaes** [comment]
If I do:
$ docker run --rm -it -v /home/ubuntu/data:/data sangerpathogens/ariba
ariba run --verbose out.card.prepareref 25164_R1.fastq.gz 25164_R2.fastq.gz
out.run

The following reads file(s) were not found:
25164_R1.fastq.gz
25164_R2.fastq.gz
Cannot continue

But they are in /home/ubuntu/data:
localadmin@HOS46582:/home/ubuntu/data$ ls
25164_R1.fastq.gz  25164_R2.fastq.gz  out.card.prepareref

**Comment by kpepper** [comment]
Yes, you need to put /data/ in front of the file args - it's the data area from the docker container's perspective:

docker run --rm -it -v /home/ubuntu/data:/data sangerpathogens/ariba ariba run --verbose /data/out.card.prepareref /data/25164_R1.fastq.gz /data/25164_R2.fastq.gz /data/out.run

**Comment by BaMagalhaes** [comment]
Yap, it worked!

Thank you very much!

**Comment by kpepper** [comment]
Great, good luck with your analysis.
