### ISSUE TITLE
v2.14.1	attributeError: 'Namespace' object has no attribute 'cdhit_max_memory'

### ISSUE THREAD

**Issue by Coldheart79** [sanger-pathogens/ariba#273]
Updated  ariba to version2.14.1 and started running in to problems, please advice, error occurs when running Task: prepareref and the same when running 'ariba test out' 

Running ARIBA on test data...
-------------------------------------------------------------------------------
|=============================================================================|
|                            Preparing input data                             |
|=============================================================================|
-------------------------------------------------------------------------------
Made output directory out. Copying test data files into it:
    copied ref_seqs.fa
    copied metadata.tsv
    copied reads_1.fq
    copied reads_2.fq
-------------------------------------------------------------------------------
|=============================================================================|
|                        Try running ariba prepareref                         |
|=============================================================================|
-------------------------------------------------------------------------------

Running ariba prepareref with:
/usr/local/bin/ariba prepareref --verbose -f ref_seqs.fa -m metadata.tsv --threads 1 PREPAREREF

ARIBA version: 2.14.1

External dependencies:
bowtie2	2.3.4.1	/usr/bin/bowtie2
cdhit	4.7	/home/ant4317/Program/cd-hit-v4.6.8/cd-hit-est
nucmer	3.1	/usr/bin/nucmer

External dependencies OK: True

Python version:
3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]

Python packages:
ariba	2.14.1	/home/ant4317/.local/lib/python3.6/site-packages/ariba/__init__.py
bs4	4.7.1	/home/ant4317/.local/lib/python3.6/site-packages/bs4/__init__.py
dendropy	4.4.0	/home/ant4317/.local/lib/python3.6/site-packages/dendropy/__init__.py
pyfastaq	3.17.0	/home/ant4317/.local/lib/python3.6/site-packages/pyfastaq/__init__.py
pymummer	0.10.3	/home/ant4317/.local/lib/python3.6/site-packages/pymummer/__init__.py
pysam	0.15.2	/home/ant4317/.local/lib/python3.6/site-packages/pysam/__init__.py

Python packages OK: True

Everything looks OK: True
Traceback (most recent call last):
  File "/usr/local/bin/ariba", line 298, in <module>
    args.func(args)
  File "/home/ant4317/.local/lib/python3.6/site-packages/ariba/tasks/prepareref.py", line 24, in run
    cdhit_max_memory=options.cdhit_max_memory,
AttributeError: 'Namespace' object has no attribute 'cdhit_max_memory'

Something went wrong. See above for error message(s). Return code was 1

**Comment by Coldheart79** [comment]
Do not know if this might be connected to the problem there is no ".local/lib/python3.6/site-packages/ariba/". Ariba is found under ".local/lib/python3.6/dist-packages/ariba/"

**Comment by kpepper** [comment]
How is your installation set up? What is getting installed here: /usr/local/bin/ariba (and which version)? Where is the new version of Ariba installed? Do you set the PYTHONPATH variable at all?

**Comment by kpepper** [comment]
Hi **@Coldheart79**. Did you manage to get your install working?

**Comment by Coldheart79** [comment]
Yes its fixed

**Comment by kpepper** [comment]
Great. I'll close the issue then.
