### ISSUE TITLE
matplotlib listed twice as a dep in setup.py

### ISSUE THREAD

**Issue by andersgs** [sanger-pathogens/ariba#275]
Hi.

`matplotlib` is listed twice as a dependency. Once with no version restrictions, and another with a restriction of at least version 3.1.0. Which one should we use? The relevant section of the setup.py file below.

Thank you for ariba? Happy to make a PR fixing this if you let me know which line is correct. I am assuming the version restricted version.

Best. Anders.

```
    install_requires=[
        'BeautifulSoup4 >= 4.1.0',
        'biopython',
        'dendropy >= 4.2.0',
        'matplotlib',
        'pyfastaq >= 3.12.0',
        'pysam >= 0.9.1',
        'pymummer<=0.10.3',
        'matplotlib>=3.1.0',
    ],
```

**Comment by kpepper** [comment]
Hi Anders,

Yes the version got increased in PR 269. >=3.1.0 should be the one to keep.
Feel free to do a PR.

Thanks.

**Comment by kpepper** [comment]
Currently merged to master. Will be in next release.
