### ISSUE TITLE
ARGannot download fails

### ISSUE THREAD

**Issue by gkapatai** [sanger-pathogens/ariba#281]
ariba getref: It seems the url used for downloading the ARGannot database is no longer valid. Can you please change it? Thanks.

**Comment by kpepper** [comment]
Hi **@gkapatai**, yes I noticed this, but haven't had a chance to fix it yet as I've been away on leave. It's on my list though.

**Comment by kpepper** [comment]
Fixed in release 2.14.4, available shortly.
