### ISSUE TITLE
Reference dataset of megares cannot be downloaded 

### ISSUE THREAD

**Issue by sgonzalezbodi** [sanger-pathogens/ariba#287]
Error "(Unexpeded header in annotations file. Expected columns: group, mechanims, header, class but got :header, type, class, mechanism.

We are using the last Ariba version (2.14.4)

**Comment by ajkarloss** [comment]
Did you get any reply/fix for that? I have the same issue

**Comment by ajkarloss** [comment]
Just to alert you to know if you get any reply?

**Comment by puethe** [comment]
Resolved in release 2.14.5
