### ISSUE TITLE
Megares Downloading Error

### ISSUE THREAD

**Issue by ajkarloss** [sanger-pathogens/ariba#294]
Command used "ariba getref megares Megares.out". Many of my colleagues are also reporting the same. 

raise Error('Unexpected header in annotations file. Expected columns: ' + ','.join(expected_columns) + ' but got: ' + ','.join(reader.fieldnames))
ariba.megares_zip_parser.Error: Unexpected header in annotations file. Expected columns: group,class,mechanism,header but got: header,type,class,mechanism,group

**Comment by puethe** [comment]
Hello @ajkarloss ,
looks like the new version of megares comes in a different format. We cannot fix that at the moment, as the software is no longer maintained. But you can constrain Ariba to download an older version as e.g. `ariba getref megares --version 1.01 Megares.out`.

**Comment by ajkarloss** [comment]
I have modified the code (megares_zip_parser.py) to parse the MEGARes 2.0.0. Shall I send a pull request?

**Comment by puethe** [comment]
Thanks, but the original developer has just put in his own [pull request](https://github.com/sanger-pathogens/ariba/pull/295/) that will be able to handle both versions 1 and 2. We will take that one.

**Comment by ajkarloss** [comment]
:) Thanks.
