### ISSUE TITLE
Using Ariba for single-end reads and fasta files

### ISSUE THREAD

**Issue by AroobAlhumaidy** [sanger-pathogens/ariba#339]
Dear Ariba developers, 

I have been exploring the capabilities of Ariba (MLST) and I'm interested by its potentials. However, I have a specific query regarding its compatibility with certain data types.

I would like to inquire if Ariba can be used effectively with single-end read raw data or a de-novo assembled fasta file. While I understand that Ariba is primarily designed for paired-end reads to ensure accurate allele calling, I am curious to know if there were any modifications that would enable its utilization with single-end read data or de-novo assembled fasta files.

I believe this information would greatly assist me in determining the suitability of Ariba for my project. Any insights or recommendations, you could provide would be highly appreciated.

Thank you very much for your time,

Best,

**Comment by martinghunt** [comment]
Ariba won't work with unpaired reads. It's all based around paired reads.

You could run on an assembly by simulating perfect paired reads from the assembly, and using those as input to Ariba.
