### ISSUE TITLE
report.tsv empty

### ISSUE THREAD

**Issue by deisyabril** [sanger-pathogens/ariba#96]
Hi, I installed all dependences for ARIBA and all the softwares are added to the path, all test passed and it installed correctly without errors.
Later, I downloaded the databases: CARD, argannot, ResFinder and VFDB, following the example in Wiki:
ariba getref card out.card
ariba prepareref --ref_prefix out.card out.card.prepareref
ariba run out.card.prepareref reads1.fastq reads2.fastq out.run

Nevertheless when I did the run task, I saw that the report.all.tsv file had many (-) symbols and the report.tsv file is empty.

![result](https://cloud.githubusercontent.com/assets/20144123/16395201/58837c64-3c7e-11e6-9bba-c45de55cacbb.png)
report.all.tsv
![report_all_tsv](https://cloud.githubusercontent.com/assets/20144123/16395232/7bb1ab34-3c7e-11e6-9db6-44537f237e0c.png)
report.tsv
![report_tsv](https://cloud.githubusercontent.com/assets/20144123/16395231/7baf1cfc-3c7e-11e6-9c57-40f7d602fff5.png)

How can I solve that?, thank you.

**Comment by martinghunt** [comment]
It's just noise, where a few reads have happened to map to some of the reference genes (see column D in report.all.tsv). None of them got assembled into anything matching the reference genes, hence the flags being 0 or 64 (column C). So when report.all.tsv is filtered to make report.tsv, there is nothing left to report.

**Comment by deisyabril** [comment]
Thanks for the information martinghunt,
